[project]
name = "gracehpc"
version = "0.1.0"
description = "HPC carbon emissions toolkit"
authors = [
    {name = "Elliot Ayliffe",email = "Elliot.ayliffe@gmail.com"}
]
readme = "README.md"
packages = [{ include = "gracehpc" }]
requires-python = ">=3.9,<3.13"
dependencies = [
    "pandas (>=2.3.0,<3.0.0)",
    "ipykernel (>=6.29.5,<7.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


