[project]
name = "grace-hpc"
version = "0.1.0"
description = "HPC carbon emissions toolkit"
authors = [
    {name = "Elliot Ayliffe",email = "Elliot.ayliffe@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
