# ----------------------------------------------------------------------------------------------------------------
# GRACE-HPC CONFIGURATION FILE - Isambard 3
# ----------------------------------------------------------------------------------------------------------------
#
# This file must be edited by the user to include their specific HPC system details before using the GRACE-HPC tool.
# Please replace all placeholders enclosed in < > with the best estimates for your HPC cluster specifications (e.g. Isambard 3, Isambard-AI etc...)
# Remove all < > brackets after filling in the values.
# See the documentation for an example configuration file (hpc_config.yaml) with the correct format.



---
# The name of your HPC system (e.g. "Isambard 3", "Isambard-AI")
hpc_system: "Isambard 3"         # (str)

# List the different partitions available on the cluster below with its hardware details (or at least the one you want to use)
partitions:                         

    # Example CPU partition 
    grace:               # E.g. For Isambard 3, this would be grace. For Isambard-AI, comment out this partition and use the GPU partition template below.
        processor: CPU             # Is the partition CPU or GPU based? E.g. Isambard 3 = CPU, Isambard-AI = GPU, Archer2 = CPU 
        processor_name: "NVIDIA Grace CPU"    # (str) The model name of the processor. E.g. "NVIDIA Grace CPU" 
        TDP: 3.472                     # (float) The thermal design power (TDP) of the processor per core in Watts. (CPU)


    # Add additional partitions as needed, following the same structure as above.

### The tools backend does not use the processor names, so they do not affect the calculations.

# Power Usage Effectiveness (PUE) of the data centre/ facility (i.e. the data centre overhead)
PUE: 1.1                # (float) E.g. Isambard-AI has an estimated PUE of 1.1

# Average cost of electricity in GBP per kWh 
electricity_cost: 0.2573            # (float)  Average Cost of electricity in the UK (0.2573 GBP/kWh) - July 2025 - https://www.ofgem.gov.uk/information-consumers/energy-advice-households/energy-price-cap





# ----------------------------------------------------------------------------------------------------------------
# SOME HELPFUL TDP VALUES:
#
# NVIDIA GRACE CPU (Isambard 3): ~ 3.472 W per Core               - (250 W/ 72 cores) https://resources.nvidia.com/en-us-grace-cpu/data-center-datasheet?ncid=no-ncid
# NVIDIA H100 Tensor Core GPU (Isambard-AI): ~ 700 W per GPU (max) - https://resources.nvidia.com/en-us-hopper-architecture/nvidia-tensor-core-gpu-datasheet?ncid=no-ncid
# ----------------------------------------------------------------------------------------------------------------